export const FETCH_TODOS = 'FETCH_TODOS'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO_ID = 'UPDATE_TODO_ID'


export const FETCH_TODOS_ACTIVE = "FETCH_TODOS_ACTIVE"
export const FETCH_TODOS_COMPLETED = "FETCH_TODOS_COMPLETED"